package com.example.pkumar.android_tutorials;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

/*The main activity code is a Java file MainActivity.java. This is the actual
       application file which ultimately gets converted to a Dalvik executable and runs your
        application.
        Following is the default code generated by the application wizard for Hello World! application*/

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
